toolsets:
  kubernetes/core:
    enabled: true
  core_investigation:
    enabled: false
  kubernetes/logs:
    enabled: false
  bash:
    enabled: false
  helm/core:
    enabled: false
  aks/core:
    enabled: true
  aks/node-health:
    enabled: false
  kubernetes/kube-prometheus-stack:
    enabled: false
  kubernetes/live-metrics:
    enabled: false
  datadog/rds:
    enabled: false
  internet:
    enabled: false
  runbook:
    enabled: false